<?php

/**
 * @file
 * Provides hook handling.
 */


use Drupal\Core\Cache\Cache;
use Drupal\localgov_roles\RolesHelper;

/**
 * Implements hook_modules_installed().
 */
function localgov_job_vacancies_modules_installed($modules, $is_syncing) {
  // Configure scheduled transitions if it's being installed.
  if (in_array('scheduled_transitions', $modules, TRUE)) {
    localgov_job_vacancies_configure_scheduled_transitions();
  }
}

/**
 * Implements hook_localgov_roles_default().
 */
function localgov_job_vacancies_localgov_roles_default() {
  // Content editing permissions.
  $perms = [
    RolesHelper::EDITOR_ROLE => [
      'create localgov_job_vacancy content',
      'delete any localgov_job_vacancy content',
      'delete localgov_job_vacancy revisions',
      'delete own localgov_job_vacancy content',
      'edit any localgov_job_vacancy content',
      'edit own localgov_job_vacancy content',
      'revert localgov_job_vacancy revisions',
      'view localgov_job_vacancy revisions',
    ],
  ];

  // Content scheduling permissions required by localgov_workflows.
  if (\Drupal::moduleHandler()->moduleExists('localgov_workflows')) {
    $perms[RolesHelper::EDITOR_ROLE] = array_merge($perms[RolesHelper::EDITOR_ROLE], [
      'add scheduled transitions node localgov_job_vacancy',
      'reschedule scheduled transitions node localgov_job_vacancy',
      'view scheduled transitions node localgov_job_vacancy',
    ]);
  }

  return $perms;
}

/**
 * Configure scheduled transitions.
 */
function localgov_job_vacancies_configure_scheduled_transitions() {
  // Configure scheduled transitions for alert banners.
  $scheduled_transitions_config = \Drupal::service('config.factory')->getEditable('scheduled_transitions.settings');
  $bundles = $scheduled_transitions_config->get('bundles');
  $bundles[] = [
    'entity_type' => 'node',
    'bundle' => 'localgov_job_vacancies',
  ];
  $scheduled_transitions_config->set('bundles', $bundles);
  $scheduled_transitions_config->save();

  Cache::invalidateTags([
    'scheduled_transition_settings',
    'config:scheduled_transitions.settings',
  ]);
}
